### ISSUE TITLE
Success Build, Failed Run Images (SyntaxError: Unexpected end of JSON input)

### ISSUE THREAD

**Issue by muhammadAgfian96** [microsoft/vscode-remote-try-node#29]
Hi, i try to using remote-containers and try vscode-remote-try-node python. and it failed. i can't figure out what happen here. its succes building image, but failed when running the image.

i'm using ubuntu 18.04.

```
[2021-06-14T09:15:13.534Z] Remote-Containers 0.183.0 in VS Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c).
[2021-06-14T09:15:13.534Z] Start: Resolving Remote
[2021-06-14T09:15:13.540Z] Setting up container for folder or workspace: path/to/here/data_structure_python
[2021-06-14T09:15:13.543Z] Start: Check Docker is running
[2021-06-14T09:15:13.543Z] Start: Run: docker version --format {{.Server.APIVersion}}
[2021-06-14T09:15:13.649Z] Stop (106 ms): Run: docker version --format {{.Server.APIVersion}}
[2021-06-14T09:15:13.649Z] Server API version: 
[2021-06-14T09:15:13.649Z] Stop (106 ms): Check Docker is running
[2021-06-14T09:15:13.656Z] Start: Run: git rev-parse --show-cdup
[2021-06-14T09:15:13.660Z] Stop (4 ms): Run: git rev-parse --show-cdup
[2021-06-14T09:15:13.662Z] Start: Run: docker ps -q -a --filter label=vsch.local.folder=path/to/here/data_structure_python --filter label=vsch.quality=stable
[2021-06-14T09:15:13.736Z] Stop (74 ms): Run: docker ps -q -a --filter label=vsch.local.folder=path/to/here/data_structure_python --filter label=vsch.quality=stable
[2021-06-14T09:15:13.738Z] Start: Run: docker build -f path/to/here/data_structure_python/.devcontainer/Dockerfile -t vsc-data_structure_python-ade5668d1463d7719d126aba2697d2b6 --build-arg VARIANT=3.9 --build-arg INSTALL_NODE=false --build-arg NODE_VERSION=lts/* path/to/here/data_structure_python
[2021-06-14T09:15:13.852Z] Sending build context to Docker daemon  557.1kB
[2021-06-14T09:15:13.853Z] Sending build context to Docker daemon  714.2kB

[2021-06-14T09:15:13.857Z] Step 1/5 : ARG VARIANT="3.9"
Step 2/5 : FROM mcr.microsoft.com/vscode/devcontainers/python:0-${VARIANT}
[2021-06-14T09:15:13.857Z]  ---> b9043162eac5
Step 3/5 : ARG INSTALL_NODE="true"
[2021-06-14T09:15:13.857Z]  ---> Using cache
 ---> c263cbc3aa4b
Step 4/5 : ARG NODE_VERSION="lts/*"
[2021-06-14T09:15:13.858Z]  ---> Using cache
 ---> 033097ed0e1c
Step 5/5 : RUN if [ "${INSTALL_NODE}" = "true" ]; then su vscode -c "umask 0002 && . /usr/local/share/nvm/nvm.sh && nvm install ${NODE_VERSION} 2>&1"; fi
[2021-06-14T09:15:13.858Z]  ---> Using cache
 ---> e446c2256cc6
[2021-06-14T09:15:13.859Z] Successfully built e446c2256cc6
[2021-06-14T09:15:13.860Z] Successfully tagged vsc-data_structure_python-ade5668d1463d7719d126aba2697d2b6:latest
[2021-06-14T09:15:13.864Z] Stop (126 ms): Run: docker build -f path/to/here/data_structure_python/.devcontainer/Dockerfile -t vsc-data_structure_python-ade5668d1463d7719d126aba2697d2b6 --build-arg VARIANT=3.9 --build-arg INSTALL_NODE=false --build-arg NODE_VERSION=lts/* path/to/here/data_structure_python
[2021-06-14T09:15:13.865Z] Start: Run: docker inspect --type image vsc-data_structure_python-ade5668d1463d7719d126aba2697d2b6
[2021-06-14T09:15:13.936Z] Stop (71 ms): Run: docker inspect --type image vsc-data_structure_python-ade5668d1463d7719d126aba2697d2b6
[2021-06-14T09:15:13.940Z] SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at Cf (/home/aiti/.vscode/extensions/ms-vscode-remote.remote-containers-0.183.0/dist/extension/extension.js:214:1206)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async fc (/home/aiti/.vscode/extensions/ms-vscode-remote.remote-containers-0.183.0/dist/extension/extension.js:214:944)
	at async fI (/home/aiti/.vscode/extensions/ms-vscode-remote.remote-containers-0.183.0/dist/extension/extension.js:250:1129)
	at async Hz (/home/aiti/.vscode/extensions/ms-vscode-remote.remote-containers-0.183.0/dist/extension/extension.js:236:10239)
	at async UD (/home/aiti/.vscode/extensions/ms-vscode-remote.remote-containers-0.183.0/dist/extension/extension.js:236:6872)
	at async wz (/home/aiti/.vscode/extensions/ms-vscode-remote.remote-containers-0.183.0/dist/extension/extension.js:217:9939)

```

Thanks.

**Comment by muhammadAgfian96** [comment]
alright, so i re-install my docker, and it works!
